general.import = ["colors.toml"]
[window]
#padding = { x = 8, y = 8 }
#dynamic_padding = true
decorations = "full"
opacity = 1.0
#startup_mode = "Windowed"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold   = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 12.0

[cursor]
style = "Beam"

#[colors.primary]
#background = "#1f1f28"
#foreground = "#c8c093"
#
#[colors.normal]
#black   = "#16161d"
#red     = "#ec5f67"
#green   = "#98bb6c"
#yellow  = "#fec418"
#blue    = "#51afef"
#magenta = "#c678dd"
#cyan    = "#2ac3de"
#white   = "#e0def4"
#
#[colors.bright]
#black   = "#65737e"
#red     = "#ec5f67"
#green   = "#9ece6a"
#yellow  = "#f6c177"
#blue    = "#51afef"
#magenta = "#c678dd"
#cyan    = "#2ac3de"
#white   = "#eff0eb"

[scrolling]
history = 10000
multiplier = 3

